import { Flow, FlowId } from './types';

/** Flux métier expliqués sans jargon (même vocabulaire que l'interface). */
export const FLOWS: Record<FlowId, Flow> = {
  purchase: {
    id: 'purchase',
    title: 'Un achat de stock',
    summary: 'Ce qui se passe quand vous achetez des ingrédients.',
    nodes: [
      { emoji: '🛒', label: 'Achat', caption: 'quantité, prix payé, source, date', tone: 'primary' },
      { emoji: '📦', label: 'Stock +', caption: 'le stock augmente tout de suite', tone: 'success' },
      { emoji: '💰', label: 'Moyen de paiement', caption: 'caisse, argent personnel, banque…', tone: 'info' },
      {
        emoji: '🏦',
        label: 'Caisse −',
        caption: 'seulement si payé avec la caisse',
        tone: 'danger',
        conditional: true,
      },
      { emoji: '📋', label: 'Commandes débloquées', caption: 'les manques sont recalculés', tone: 'success' },
    ],
    note: "Payé avec votre argent personnel ou la banque : le stock augmente, la caisse ne bouge pas.",
  },
  sale: {
    id: 'sale',
    title: 'Une vente',
    summary: 'Vendre et encaisser sont deux choses différentes.',
    nodes: [
      { emoji: '🧁', label: 'Commande confirmée', caption: 'c’est une vente', tone: 'primary' },
      { emoji: '🧾', label: 'Chiffre d’affaires +', caption: 'compté, payé ou non', tone: 'info' },
      { emoji: '⏳', label: 'À encaisser', caption: 'tant que le client n’a pas payé', tone: 'warning' },
      { emoji: '💰', label: 'Paiement', caption: 'vous cliquez sur « Encaisser »', tone: 'success' },
      { emoji: '🏦', label: 'Caisse +', caption: 'l’argent est dans la caisse', tone: 'success' },
    ],
    note: 'Le paiement peut arriver avant, pendant ou après la préparation.',
  },
  missing: {
    id: 'missing',
    title: 'Une commande avec un ingrédient manquant',
    summary: 'Vous pouvez quand même prendre la commande.',
    nodes: [
      { emoji: '👤', label: 'Client', tone: 'neutral' },
      { emoji: '🧾', label: 'Commande créée', caption: 'le stock ne bouge pas encore', tone: 'primary' },
      { emoji: '⚠️', label: 'Manque détecté', caption: 'ajouté à la liste de courses', tone: 'danger' },
      { emoji: '🛒', label: 'Achat', caption: 'depuis la liste de courses', tone: 'primary' },
      { emoji: '📦', label: 'Stock suffisant', tone: 'success' },
      { emoji: '🟢', label: 'Préparation possible', caption: 'les ingrédients sont utilisés à ce moment', tone: 'success' },
    ],
  },
  payment: {
    id: 'payment',
    title: 'Avancement et paiement',
    summary: 'Deux suivis séparés : ce qui est fait, et ce qui est payé.',
    nodes: [
      { emoji: '📝', label: 'En attente → Confirmée', tone: 'info' },
      { emoji: '👩‍🍳', label: 'En préparation', caption: 'les ingrédients sont utilisés', tone: 'primary' },
      { emoji: '🎂', label: 'Prête', tone: 'success' },
      { emoji: '🤝', label: 'Remise au client', tone: 'violet' },
      { emoji: '💰', label: 'Paiement, à tout moment', caption: 'non payée · partiel · payée', tone: 'success', conditional: true },
    ],
    note: 'Une commande peut être prête et pas encore payée : elle apparaît dans « À encaisser ».',
  },
  cancel: {
    id: 'cancel',
    title: 'Annuler une commande',
    summary: 'Ce qui se passe selon le moment de l’annulation.',
    nodes: [
      { emoji: '🧾', label: 'Avant la préparation', caption: 'rien n’a été utilisé, les achats prévus sont libérés', tone: 'info' },
      { emoji: '👩‍🍳', label: 'Après le début', caption: 'une raison est demandée', tone: 'warning' },
      { emoji: '📦', label: 'Ingrédients', caption: 'déjà utilisés : ils ne reviennent pas tout seuls', tone: 'danger' },
      { emoji: '💸', label: 'Argent reçu', caption: 'reste en caisse jusqu’au remboursement', tone: 'neutral', conditional: true },
    ],
  },
  'order-check': {
    id: 'order-check',
    title: 'Du client à la préparation',
    summary: 'Ce que l’application vérifie pour chaque commande.',
    nodes: [
      { emoji: '🧾', label: 'Commande enregistrée', caption: 'même s’il manque un ingrédient', tone: 'primary' },
      { emoji: '📦', label: 'Stock disponible ?', caption: 'calcul automatique', tone: 'info' },
      { emoji: '🟢', label: 'Oui → préparation possible', tone: 'success' },
      { emoji: '⚠️', label: 'Non → besoin d’achat', caption: 'ajouté à la liste de courses', tone: 'danger', conditional: true },
      { emoji: '🛒', label: 'Achat', caption: 'depuis la liste de courses', tone: 'primary', conditional: true },
      { emoji: '📦', label: 'Stock +', tone: 'success', conditional: true },
      { emoji: '👩‍🍳', label: 'Préparation', caption: 'les ingrédients sont utilisés à ce moment-là', tone: 'success' },
    ],
    note: 'Le manque ne bloque que la préparation, jamais l’enregistrement de la commande.',
  },
  cash: {
    id: 'cash',
    title: 'Ce qui fait bouger la caisse',
    summary: 'Entrées, dépenses et achats : qui touche la caisse ?',
    nodes: [
      { emoji: '➕', label: 'Entrée', caption: 'argent qui entre → caisse +', tone: 'success' },
      { emoji: '➖', label: 'Dépense payée avec la caisse', caption: 'caisse −', tone: 'danger' },
      { emoji: '🛒', label: 'Achat payé avec la caisse', caption: 'stock + et caisse −', tone: 'primary' },
      { emoji: '👤', label: 'Achat payé avec votre argent', caption: 'stock +, caisse inchangée', tone: 'neutral', conditional: true },
      { emoji: '💰', label: 'Commande encaissée', caption: 'caisse + et « à encaisser » −', tone: 'success' },
    ],
    note: 'Vendre ne remplit pas la caisse : seul l’encaissement le fait.',
  },
  stock: {
    id: 'stock',
    title: 'La vie du stock',
    summary: 'D’où vient le stock et quand il diminue.',
    nodes: [
      { emoji: '🛒', label: 'Achat', caption: 'le stock augmente', tone: 'success' },
      { emoji: '📦', label: 'Stock actuel', caption: 'comparé au seuil d’alerte que vous choisissez', tone: 'info' },
      { emoji: '🧾', label: 'Commandes prévues', caption: 'réservent le stock sans le retirer', tone: 'neutral' },
      { emoji: '⚠️', label: 'Manque', caption: 'si les commandes demandent plus que le stock', tone: 'danger', conditional: true },
      { emoji: '👩‍🍳', label: 'Consommation', caption: 'au début de la préparation, une seule fois', tone: 'primary' },
      { emoji: '✏️', label: 'Correction', caption: 'inventaire, perte, casse — avec une raison', tone: 'violet', conditional: true },
      { emoji: '📜', label: 'Historique', caption: 'chaque mouvement est noté', tone: 'neutral' },
    ],
  },
  stats: {
    id: 'stats',
    title: 'Vendu ≠ dans la caisse',
    summary: '« J’ai vendu 500 DT » n’est pas « j’ai 500 DT dans la caisse ».',
    nodes: [
      { emoji: '🧾', label: 'Chiffre d’affaires', caption: 'ce que vous avez vendu, payé ou non', tone: 'primary' },
      { emoji: '💵', label: 'Encaissements', caption: 'l’argent réellement reçu des clients', tone: 'success' },
      { emoji: '⏳', label: 'À encaisser', caption: 'vendu mais pas encore payé', tone: 'warning' },
      { emoji: '🏦', label: 'Liquidité', caption: 'l’argent présent dans la caisse', tone: 'violet' },
      { emoji: '🛒', label: 'Achats', caption: 'ingrédients achetés (caisse ou non)', tone: 'info' },
      { emoji: '➖', label: 'Dépenses', caption: 'emballages, gaz… (caisse ou non)', tone: 'danger' },
    ],
    note: 'Exemple : 500 DT vendus dont 300 DT payés → caisse +300 DT, 200 DT à encaisser.',
  },
  recipe: {
    id: 'recipe',
    title: 'Une recette et son prix',
    summary: 'Comment le prix d’une recette est calculé.',
    nodes: [
      { emoji: '🎂', label: 'Recette', tone: 'primary' },
      { emoji: '📏', label: 'Tailles et portions', caption: 'chaque taille a ses propres quantités', tone: 'info' },
      { emoji: '🥚', label: 'Ingrédients', caption: 'quantité × prix de l’ingrédient = coût', tone: 'success' },
      { emoji: '🔥', label: 'Machines et temps', caption: 'électricité selon la puissance et la durée', tone: 'warning' },
      { emoji: '💧', label: 'Eau', caption: 'forfait réglé dans les paramètres', tone: 'info' },
      { emoji: '➕', label: 'Marge', caption: 'pourcentage réglé dans les paramètres', tone: 'violet' },
      { emoji: '🏷️', label: 'Prix de vente', caption: 'le client voit le prix, jamais la préparation', tone: 'primary' },
    ],
  },
  shopping: {
    id: 'shopping',
    title: 'Pourquoi cet ingrédient est dans la liste',
    summary: 'De la commande bloquée à la commande débloquée.',
    nodes: [
      { emoji: '🧾', label: 'Commandes prévues', caption: 'CMD-12 → 0,3 kg · CMD-15 → 0,5 kg', tone: 'primary' },
      { emoji: '📦', label: 'Stock insuffisant', caption: 'il manque 0,8 kg d’amandes', tone: 'danger' },
      { emoji: '🏪', label: 'Source et dernier prix', caption: 'où l’acheter et combien il a coûté', tone: 'info' },
      { emoji: '🛒', label: 'Acheter', caption: 'quantité, prix payé, moyen de paiement', tone: 'primary' },
      { emoji: '🟢', label: 'Commandes débloquées', caption: 'les plus proches d’abord', tone: 'success' },
    ],
    note: 'Achat partiel : le stock acheté sert d’abord la commande la plus proche.',
  },
};
